/**
 * 支付系统错误码常量定义
 */
const ERROR_CODES = {
  // 签名相关错误
  INVALID_SIGNATURE: 'INVALID_SIGNATURE',
  SIGNATURE_GENERATION_FAILED: 'SIGNATURE_GENERATION_FAILED',
  
  // 支付相关错误
  PAYMENT_FAILED: 'PAYMENT_FAILED',
  PAYMENT_TIMEOUT: 'PAYMENT_TIMEOUT',
  PAYMENT_CANCELLED: 'PAYMENT_CANCELLED',
  
  // 订单相关错误
  ORDER_NOT_FOUND: 'ORDER_NOT_FOUND',
  ORDER_STATUS_ERROR: 'ORDER_STATUS_ERROR',
  ORDER_CREATION_FAILED: 'ORDER_CREATION_FAILED',
  
  // 参数验证错误
  INVALID_AMOUNT: 'INVALID_AMOUNT',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  MISSING_REQUIRED_PARAMS: 'MISSING_REQUIRED_PARAMS',
  
  // 网络和系统错误
  NETWORK_ERROR: 'NETWORK_ERROR',
  CONFIG_ERROR: 'CONFIG_ERROR',
  DATABASE_ERROR: 'DATABASE_ERROR',
  
  // 回调处理错误
  CALLBACK_ERROR: 'CALLBACK_ERROR',
  NOTIFY_VERIFICATION_FAILED: 'NOTIFY_VERIFICATION_FAILED',
  
  // 通用错误
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  UNKNOWN_ERROR: 'UNKNOWN_ERROR'
};

/**
 * 错误消息映射
 */
const ERROR_MESSAGES = {
  [ERROR_CODES.INVALID_SIGNATURE]: '签名验证失败',
  [ERROR_CODES.SIGNATURE_GENERATION_FAILED]: '签名生成失败',
  [ERROR_CODES.PAYMENT_FAILED]: '支付处理失败',
  [ERROR_CODES.PAYMENT_TIMEOUT]: '支付超时',
  [ERROR_CODES.PAYMENT_CANCELLED]: '支付已取消',
  [ERROR_CODES.ORDER_NOT_FOUND]: '订单不存在',
  [ERROR_CODES.ORDER_STATUS_ERROR]: '订单状态异常',
  [ERROR_CODES.ORDER_CREATION_FAILED]: '订单创建失败',
  [ERROR_CODES.INVALID_AMOUNT]: '支付金额无效',
  [ERROR_CODES.VALIDATION_ERROR]: '参数验证失败',
  [ERROR_CODES.MISSING_REQUIRED_PARAMS]: '缺少必需参数',
  [ERROR_CODES.NETWORK_ERROR]: '网络连接异常',
  [ERROR_CODES.CONFIG_ERROR]: '系统配置错误',
  [ERROR_CODES.DATABASE_ERROR]: '数据存储错误',
  [ERROR_CODES.CALLBACK_ERROR]: '回调处理失败',
  [ERROR_CODES.NOTIFY_VERIFICATION_FAILED]: '通知验证失败',
  [ERROR_CODES.INTERNAL_ERROR]: '系统内部错误',
  [ERROR_CODES.UNKNOWN_ERROR]: '未知错误'
};

/**
 * HTTP 状态码映射
 */
const HTTP_STATUS_CODES = {
  [ERROR_CODES.INVALID_SIGNATURE]: 400,
  [ERROR_CODES.SIGNATURE_GENERATION_FAILED]: 500,
  [ERROR_CODES.PAYMENT_FAILED]: 400,
  [ERROR_CODES.PAYMENT_TIMEOUT]: 408,
  [ERROR_CODES.PAYMENT_CANCELLED]: 400,
  [ERROR_CODES.ORDER_NOT_FOUND]: 404,
  [ERROR_CODES.ORDER_STATUS_ERROR]: 400,
  [ERROR_CODES.ORDER_CREATION_FAILED]: 500,
  [ERROR_CODES.INVALID_AMOUNT]: 400,
  [ERROR_CODES.VALIDATION_ERROR]: 400,
  [ERROR_CODES.MISSING_REQUIRED_PARAMS]: 400,
  [ERROR_CODES.NETWORK_ERROR]: 503,
  [ERROR_CODES.CONFIG_ERROR]: 500,
  [ERROR_CODES.DATABASE_ERROR]: 500,
  [ERROR_CODES.CALLBACK_ERROR]: 500,
  [ERROR_CODES.NOTIFY_VERIFICATION_FAILED]: 400,
  [ERROR_CODES.INTERNAL_ERROR]: 500,
  [ERROR_CODES.UNKNOWN_ERROR]: 500
};

module.exports = {
  ERROR_CODES,
  ERROR_MESSAGES,
  HTTP_STATUS_CODES
};