version: '3.8'

services:
  alipay-payment:
    build: .
    container_name: alipay-payment-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    env_file:
      - .env.production
    volumes:
      - ./logs:/app/logs
      - ./keys:/app/keys:ro
      - ./data:/app/data
    networks:
      - alipay-network
    depends_on:
      - redis
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  redis:
    image: redis:7-alpine
    container_name: alipay-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - alipay-network
    command: redis-server --appendonly yes

  nginx:
    image: nginx:alpine
    container_name: alipay-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    networks:
      - alipay-network
    depends_on:
      - alipay-payment

volumes:
  redis_data:

networks:
  alipay-network:
    driver: bridge