name: 应用构建

on:
  push:
    tags:
      - 'v*'
    branches:
      - main
  workflow_dispatch:

jobs:
  build-mac:
    runs-on: macos-latest
    env:
      VITE_API_URL: ${{ secrets.VITE_API_URL }}
    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 设置Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: 安装 pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false

      - name: 获取 pnpm 缓存路径
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - name: 设置 pnpm 缓存
        uses: actions/cache@v3
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: 安装依赖
        run: pnpm install

      - name: 构建Mac版本
        run: pnpm run build:mac

      - name: 上传Mac构建产物
        uses: actions/upload-artifact@v4
        with:
          name: mac-build
          path: |
            dist/*.dmg
            dist/*.zip

  build-win:
    runs-on: windows-latest
    env:
      VITE_API_URL: ${{ secrets.VITE_API_URL }}
    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 设置Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: 安装 pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false

      - name: 获取 pnpm 缓存路径
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - name: 设置 pnpm 缓存
        uses: actions/cache@v3
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: 安装依赖
        run: |
          pnpm install
          pnpm add @element-plus/icons-vue

      - name: 构建Windows版本
        run: pnpm run build:win

      - name: 上传Windows构建产物
        uses: actions/upload-artifact@v4
        with:
          name: win-build
          path: dist/*.exe

  create-release:
    needs: [build-mac, build-win]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: 下载所有构建产物
        uses: actions/download-artifact@v4

      - name: 创建发布版本
        uses: softprops/action-gh-release@v1
        with:
          files: |
            mac-build/**
            win-build/**
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 